# Import the random libary
import random

# All the prompt choices
prompts = [
    "Combine an elephant with a bike",
    "Huston, we have a problem",
    "Combine a couch with a surf board",
    "A vegetable house",
    "A clock made from glasses",
    "What would make finding a tv remote easier?",
    "Happiness",
    "Sadness",
    "A magnetic book",
    "A dollar tree",
    "A reusable fruit straw",
    "Bigger is better",
    "What is useless?",
    "Add a bar stand to a fruit",
    "Empire state of mind",
    "How does the future of north pole look like?",
    "Reverse a flower vase",
    "A chopstick spoon",
    "A pencilpen",
    "Reuse a shelf",
    "Breathing icon",
    "A butter glue",
    "Upside down beer bottle",
    "I'm the king of the world!",
    "There's no place like home.",
    "Upside down Birthday cake",
    "Cactus with a cowboy hat",
    "A House with a round roof",
    "A banana in a boat",
    "A Cucumber playing a Guitar",
    "A Flower with candy inside",
    "A Racing car",
    "A Spider swimming in the river",
    "A crab building a sand castle",
    "A table in the sea",
    "Kangaroos getting married",
    "An Orange throwing a ball",
    "Framed Christmas Tree",
    "A Frog with glasses",
    "A Lemon on top of Mount Everest",
    "A Butterfly flying to the Sun",
    "A Mannequin head on fire",
    "A Goat playing video games",
    "A pen as a foot",
    "A polar bear harvesting coconuts",
    "A Giraffe drinking wine",
    "Hot air baloon as a light bulb",
    "A Scarecrow in a dress",
    "A Pineapple driving a car",
    "A flamingo riding a skateboard",
    "Houston, we have a pizza delivery!",
    "Combine a hammock with a jet ski",
    "A broccoli castle with carrot towers",
    "How does happiness look like?",
    "The art of expressing sadness through dance",
    "A state of mind where dreams reach for the sky",
    "Conversations that take place while skydiving",
    "A mischievous squirrel stealing a picnic basket",
    "A friendly octopus playing the drums",
    "A magical treehouse hidden deep in the forest",
    "A group of penguins having a dance party on ice",
    "A hot air balloon festival in the sky",
    "A playful dolphin jumping over a rainbow",
    "A cozy campfire scene with marshmallows roasting",
]


# Returns a random prompt from the list of prompts
def get_prompt():
    return random.choice(prompts)
